### ISSUE TITLE
Package.loadSettings is deprecated.

### ISSUE THREAD

**Issue by MeganVirus** [backjo/language-scheme#6]
Store package settings files in the settings/ directory instead of scoped-properties/
Called 1 timeCreate Issue on language-scheme repo

Package.loadSettings - /Applications/Atom.app/Contents/Resources/app/src/package.js:550:9
<unknown> - /Applications/Atom.app/Contents/Resources/app/src/package.js:172:43

can you help me? This message was shown when I opened my Atom, what I can do?

my email abel.archila@gmail.com

**Comment by vypr** [comment]
+1

Nothing you can do except fix it on your own, unless @backjo decides to fix it. It'll work fine on its own for now, but future versions of Atom might not be compatible with this issue.

**Comment by backjo** [comment]
I'll look into it over the next few days. Thanks for the heads up!

**Comment by backjo** [comment]
Fixed in v1.4.0. Thanks for the heads up @MeganVirus
